gripper_right_controller:
  ros__parameters:
    type: "joint_trajectory_controller/JointTrajectoryController"
    joints:
      - gripper_right_joint
    command_interfaces:
      - position
    state_interfaces:
      - position      
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      gripper_right_joint:
        goal: 0.02
