head_controller:
  ros__parameters:
    type: "joint_trajectory_controller/JointTrajectoryController"
    joints:
      - head_1_joint
      - head_2_joint
    command_interfaces:
      - position
    state_interfaces:
      - position

    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance:  0.05
      head_1_joint:
        goal:  0.02
      head_2_joint:
        goal: 0.02

    pan_link:  head_1_link
    tilt_link: head_2_link
    success_angle_threshold: 0.01
