leg_right_controller:
  ros__parameters:
    type: "joint_trajectory_controller/JointTrajectoryController"
    joints:
      - leg_right_1_joint
      - leg_right_2_joint
      - leg_right_3_joint
      - leg_right_4_joint
      - leg_right_5_joint
      - leg_right_6_joint
    command_interfaces:
      - position
    state_interfaces:
      - position        
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      leg_right_1_joint:
        goal: 0.02
      leg_right_2_joint:
        goal: 0.02
      leg_right_3_joint:
        goal: 0.02
      leg_right_4_joint:
        goal: 0.02
      leg_right_5_joint:
        goal: 0.02
      leg_right_6_joint:
        goal: 0.02

