leg_left_controller:
  ros__parameters: 
    type: "joint_trajectory_controller/JointTrajectoryController"
    joints:
      - leg_left_1_joint
      - leg_left_2_joint
      - leg_left_3_joint
      - leg_left_4_joint
      - leg_left_5_joint
      - leg_left_6_joint
    command_interfaces:
      - position
    state_interfaces:
      - position        
    constraints:
      goal_time: &goal_time_constraint 0.6
      stopped_velocity_tolerance: &stopped_velocity_constraint 0.05
      leg_left_1_joint:
        goal: 0.02
      leg_left_2_joint:
        goal: 0.02
      leg_left_3_joint:
        goal: 0.02
      leg_left_4_joint:
        goal: 0.02
      leg_left_5_joint:
        goal: 0.02
      leg_left_6_joint:
        goal: 0.02