torso_controller:
  ros__parameters:
    type: "joint_trajectory_controller/JointTrajectoryController"
    joints:
      - torso_1_joint
      - torso_2_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      torso_1_joint:
        goal: 0.02
      torso_2_joint:
        goal: 0.02

