ankle_right_ft_broadcaster:
  ros__parameters:
    type: "force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster"
    frame_id: ankle_right_ft_link
    sensor_name: ankle_right_ft_sensor
    update_rate: 50
    publish_rate: 50