wrist_left_ft_broadcaster:
  ros__parameters:
    type: "force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster"
    frame_id: wrist_left_ft_link
    sensor_name: wrist_left_ft_sensor
    update_rate: 50
    publish_rate: 50