play_motion2:
  ros__parameters:
    motion_planner:
      disable_motion_planning: false
      planning_groups:
        - left_arm
        - right_arm
        - torso
        - both_arms_torso
        - left_leg
        - right_leg
        - both_legs
      exclude_from_planning_joints:
        - head_1_joint
        - head_2_joint
        - gripper_right_joint
        - gripper_left_joint
      joint_tolerance: 0.01
      
      # Parameters for non-planned approach
      approach_velocity: 0.5
      approach_min_duration: 0.5
