ros__parameters:
	## Follow the following format to set the robot specific parameters to each joint
	
	# leg_right_5_joint:
	#   impedance_params:
	#     stiffness_factor: 0.0
	#     damping_factor: 0.0
	
